# exercicios.py

exercicios_por_grupo = {
    "peito": [
        {"nome": "Supino reto com barra", "series": 4, "repeticoes": 10, "equipamento": "Barra"},
        {"nome": "Supino inclinado com halteres", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Crossover", "series": 3, "repeticoes": 15, "equipamento": "Cabo"},
        {"nome": "Flexão de braço", "series": 3, "repeticoes": 12, "equipamento": "Corpo livre"},
        {"nome": "Peck deck", "series": 3, "repeticoes": 12, "equipamento": "Máquina"},
        {"nome": "Supino declinado", "series": 4, "repeticoes": 10, "equipamento": "Barra"},
        {"nome": "Crucifixo inclinado", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Flexão diamante", "series": 3, "repeticoes": 10, "equipamento": "Corpo livre"},
    ],
    "costas": [
        {"nome": "Puxada frontal", "series": 4, "repeticoes": 10, "equipamento": "Máquina"},
        {"nome": "Remada curvada", "series": 4, "repeticoes": 10, "equipamento": "Barra"},
        {"nome": "Remada unilateral", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Levantamento terra", "series": 4, "repeticoes": 8, "equipamento": "Barra"},
        {"nome": "Puxada supinada", "series": 3, "repeticoes": 12, "equipamento": "Máquina"},
        {"nome": "Remada baixa", "series": 4, "repeticoes": 10, "equipamento": "Máquina"},
        {"nome": "Barra fixa", "series": 3, "repeticoes": 8, "equipamento": "Corpo livre"},
        {"nome": "Pull-over", "series": 3, "repeticoes": 12, "equipamento": "Haltere"},
    ],
    "pernas": [
        {"nome": "Agachamento livre", "series": 4, "repeticoes": 10, "equipamento": "Barra"},
        {"nome": "Leg press", "series": 4, "repeticoes": 12, "equipamento": "Máquina"},
        {"nome": "Extensão de pernas", "series": 3, "repeticoes": 15, "equipamento": "Máquina"},
        {"nome": "Flexão de pernas", "series": 3, "repeticoes": 15, "equipamento": "Máquina"},
        {"nome": "Afundo", "series": 3, "repeticoes": 12, "equipamento": "Haltere"},
        {"nome": "Agachamento sumô", "series": 4, "repeticoes": 12, "equipamento": "Haltere"},
        {"nome": "Stiff", "series": 4, "repeticoes": 10, "equipamento": "Barra"},
        {"nome": "Panturrilha em pé", "series": 4, "repeticoes": 20, "equipamento": "Máquina"},
    ],
    "ombros": [
        {"nome": "Desenvolvimento com halteres", "series": 4, "repeticoes": 10, "equipamento": "Halteres"},
        {"nome": "Elevação lateral", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Elevação frontal", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Desenvolvimento Arnold", "series": 3, "repeticoes": 10, "equipamento": "Halteres"},
        {"nome": "Remada alta", "series": 3, "repeticoes": 10, "equipamento": "Barra"},
        {"nome": "Crucifixo inverso", "series": 3, "repeticoes": 12, "equipamento": "Máquina"},
        {"nome": "Puxada facepull", "series": 3, "repeticoes": 15, "equipamento": "Cabo"},
        {"nome": "Desenvolvimento militar", "series": 4, "repeticoes": 8, "equipamento": "Barra"},
    ],
    "bíceps": [
        {"nome": "Rosca direta", "series": 4, "repeticoes": 10, "equipamento": "Barra"},
        {"nome": "Rosca alternada", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Rosca martelo", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Rosca concentrada", "series": 3, "repeticoes": 10, "equipamento": "Halteres"},
        {"nome": "Rosca scott", "series": 3, "repeticoes": 12, "equipamento": "Máquina"},
        {"nome": "Rosca inversa", "series": 3, "repeticoes": 12, "equipamento": "Barra"},
        {"nome": "Rosca com corda", "series": 3, "repeticoes": 12, "equipamento": "Cabo"},
        {"nome": "Rosca 21", "series": 3, "repeticoes": 21, "equipamento": "Barra"},
    ],
    "tríceps": [
        {"nome": "Tríceps pulley", "series": 4, "repeticoes": 12, "equipamento": "Cabo"},
        {"nome": "Tríceps testa", "series": 3, "repeticoes": 10, "equipamento": "Barra"},
        {"nome": "Mergulho entre bancos", "series": 3, "repeticoes": 12, "equipamento": "Corpo livre"},
        {"nome": "Tríceps francês", "series": 3, "repeticoes": 10, "equipamento": "Halteres"},
        {"nome": "Tríceps coice", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Tríceps corda", "series": 3, "repeticoes": 12, "equipamento": "Cabo"},
        {"nome": "Tríceps banco", "series": 3, "repeticoes": 10, "equipamento": "Banco"},
        {"nome": "Tríceps kickback", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
    ],
    "abdômen": [
        {"nome": "Abdominal supra", "series": 3, "repeticoes": 20, "equipamento": "Colchonete"},
        {"nome": "Prancha", "series": 3, "repeticoes": 30, "equipamento": "Corpo livre"},
        {"nome": "Elevação de pernas", "series": 3, "repeticoes": 15, "equipamento": "Banco"},
        {"nome": "Abdominal infra", "series": 3, "repeticoes": 20, "equipamento": "Colchonete"},
        {"nome": "Abdominal oblíquo", "series": 3, "repeticoes": 20, "equipamento": "Colchonete"},
        {"nome": "Prancha lateral", "series": 3, "repeticoes": 30, "equipamento": "Colchonete"},
        {"nome": "Abdominal na máquina", "series": 3, "repeticoes": 15, "equipamento": "Máquina"},
        {"nome": "Abdominal com peso", "series": 3, "repeticoes": 12, "equipamento": "Anilha"},
    ],
    "trapézio": [
        {"nome": "Encolhimento com barra", "series": 4, "repeticoes": 12, "equipamento": "Barra"},
        {"nome": "Encolhimento com halteres", "series": 4, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Remada alta", "series": 3, "repeticoes": 10, "equipamento": "Barra"},
        {"nome": "Encolhimento na máquina", "series": 4, "repeticoes": 12, "equipamento": "Máquina"},
        {"nome": "Encolhimento com corda", "series": 3, "repeticoes": 15, "equipamento": "Cabo"},
        {"nome": "Face pull", "series": 3, "repeticoes": 15, "equipamento": "Cabo"},
        {"nome": "Puxada para o queixo", "series": 3, "repeticoes": 12, "equipamento": "Barra"},
        {"nome": "Remada em pé", "series": 3, "repeticoes": 12, "equipamento": "Haltere"},
    ],
}
