exercicios = {
    "peito": [
        {"nome": "Supino reto", "series": 4, "repeticoes": 10, "equipamento": "barra"},
        {"nome": "Supino inclinado com halteres", "series": 4, "repeticoes": 10, "equipamento": "halteres"},
        {"nome": "Crossover", "series": 3, "repeticoes": 12, "equipamento": "polia"},
        {"nome": "Peck deck", "series": 3, "repeticoes": 12, "equipamento": "máquina"},
        {"nome": "Flexões de braço", "series": 3, "repeticoes": 15, "equipamento": "peso corporal"},
        {"nome": "Supino declinado", "series": 4, "repeticoes": 10, "equipamento": "barra"},
        {"nome": "Pullover com halteres", "series": 3, "repeticoes": 12, "equipamento": "halteres"},
        {"nome": "Flexão com pegada fechada", "series": 3, "repeticoes": 12, "equipamento": "peso corporal"},
    ],
    "costas": [
        {"nome": "Puxada frontal", "series": 4, "repeticoes": 10, "equipamento": "polia"},
        {"nome": "Remada curvada", "series": 4, "repeticoes": 10, "equipamento": "barra"},
        {"nome": "Remada unilateral", "series": 3, "repeticoes": 12, "equipamento": "halteres"},
        {"nome": "Levantamento terra", "series": 4, "repeticoes": 6, "equipamento": "barra"},
        {"nome": "Pull-over na polia", "series": 3, "repeticoes": 12, "equipamento": "polia"},
        {"nome": "Remada baixa", "series": 4, "repeticoes": 10, "equipamento": "máquina"},
        {"nome": "Barra fixa", "series": 3, "repeticoes": 10, "equipamento": "peso corporal"},
        {"nome": "Remada cavalinho", "series": 3, "repeticoes": 10, "equipamento": "máquina"},
    ],
    "ombros": [
        {"nome": "Desenvolvimento com barra", "series": 4, "repeticoes": 10, "equipamento": "barra"},
        {"nome": "Elevação lateral", "series": 3, "repeticoes": 12, "equipamento": "halteres"},
        {"nome": "Elevação frontal", "series": 3, "repeticoes": 12, "equipamento": "halteres"},
        {"nome": "Desenvolvimento Arnold", "series": 4, "repeticoes": 10, "equipamento": "halteres"},
        {"nome": "Remada alta", "series": 3, "repeticoes": 12, "equipamento": "barra"},
        {"nome": "Crucifixo inverso", "series": 3, "repeticoes": 12, "equipamento": "máquina"},
        {"nome": "Face pull", "series": 3, "repeticoes": 15, "equipamento": "polia"},
        {"nome": "Pike push-up", "series": 3, "repeticoes": 15, "equipamento": "peso corporal"},
    ],
    "braços": [
        {"nome": "Rosca direta", "series": 4, "repeticoes": 10, "equipamento": "barra"},
        {"nome": "Rosca martelo", "series": 3, "repeticoes": 12, "equipamento": "halteres"},
        {"nome": "Tríceps testa", "series": 4, "repeticoes": 10, "equipamento": "barra"},
        {"nome": "Tríceps pulley", "series": 3, "repeticoes": 12, "equipamento": "polia"},
        {"nome": "Rosca concentrada", "series": 3, "repeticoes": 12, "equipamento": "halteres"},
        {"nome": "Tríceps banco", "series": 3, "repeticoes": 15, "equipamento": "peso corporal"},
        {"nome": "Rosca inversa", "series": 3, "repeticoes": 12, "equipamento": "barra"},
        {"nome": "Tríceps francês", "series": 3, "repeticoes": 12, "equipamento": "halteres"},
    ],
    "pernas": [
        {"nome": "Agachamento livre", "series": 4, "repeticoes": 10, "equipamento": "barra"},
        {"nome": "Leg press", "series": 4, "repeticoes": 12, "equipamento": "máquina"},
        {"nome": "Cadeira extensora", "series": 3, "repeticoes": 15, "equipamento": "máquina"},
        {"nome": "Mesa flexora", "series": 3, "repeticoes": 15, "equipamento": "máquina"},
        {"nome": "Afundo com halteres", "series": 3, "repeticoes": 12, "equipamento": "halteres"},
        {"nome": "Stiff", "series": 3, "repeticoes": 12, "equipamento": "barra"},
        {"nome": "Cadeira adutora", "series": 3, "repeticoes": 15, "equipamento": "máquina"},
        {"nome": "Panturrilha no leg", "series": 3, "repeticoes": 20, "equipamento": "máquina"},
    ],
    "abdômen": [
        {"nome": "Abdominal tradicional", "series": 3, "repeticoes": 20, "equipamento": "peso corporal"},
        {"nome": "Prancha", "series": 3, "repeticoes": 60, "equipamento": "peso corporal"},
        {"nome": "Elevação de pernas", "series": 3, "repeticoes": 15, "equipamento": "peso corporal"},
        {"nome": "Abdominal na polia", "series": 3, "repeticoes": 15, "equipamento": "polia"},
        {"nome": "Abdominal oblíquo", "series": 3, "repeticoes": 20, "equipamento": "peso corporal"},
        {"nome": "Prancha lateral", "series": 3, "repeticoes": 30, "equipamento": "peso corporal"},
        {"nome": "Bicicleta no solo", "series": 3, "repeticoes": 30, "equipamento": "peso corporal"},
        {"nome": "Crunch na bola", "series": 3, "repeticoes": 20, "equipamento": "bola suíça"},
    ],
    "trapézio": [
        {"nome": "Encolhimento com barra", "series": 3, "repeticoes": 12, "equipamento": "barra"},
        {"nome": "Encolhimento com halteres", "series": 3, "repeticoes": 12, "equipamento": "halteres"},
        {"nome": "Encolhimento na máquina", "series": 3, "repeticoes": 12, "equipamento": "máquina"},
        {"nome": "Remada alta", "series": 3, "repeticoes": 10, "equipamento": "barra"},
        {"nome": "Puxada para trapézio", "series": 3, "repeticoes": 10, "equipamento": "polia"},
        {"nome": "Face pull", "series": 3, "repeticoes": 12, "equipamento": "polia"},
        {"nome": "Shrug unilateral", "series": 3, "repeticoes": 12, "equipamento": "halteres"},
        {"nome": "Trap raise", "series": 3, "repeticoes": 15, "equipamento": "halteres"},
    ]
}
