EXERCICIOS_POR_GRUPO = {
    "Peito": [
        {"nome": "Supino reto", "nivel": "Iniciante", "series": 3, "repeticoes": 10, "equipamento": "Barra"},
        {"nome": "Supino inclinado com halteres", "nivel": "Intermediário", "series": 4, "repeticoes": 8, "equipamento": "Halteres"},
        {"nome": "Crucifixo reto", "nivel": "Iniciante", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Crossover", "nivel": "Intermediário", "series": 4, "repeticoes": 10, "equipamento": "Crossover"},
        {"nome": "Peck Deck", "nivel": "Iniciante", "series": 3, "repeticoes": 12, "equipamento": "Máquina"},
        {"nome": "Flexões de braço", "nivel": "Iniciante", "series": 3, "repeticoes": 15, "equipamento": "Corpo livre"},
        {"nome": "Supino declinado", "nivel": "Avançado", "series": 4, "repeticoes": 8, "equipamento": "Barra"},
        {"nome": "Crucifixo inclinado", "nivel": "Avançado", "series": 3, "repeticoes": 10, "equipamento": "Halteres"},
    ],
    "Costas": [
        {"nome": "Puxada frente", "nivel": "Iniciante", "series": 3, "repeticoes": 10, "equipamento": "Polia"},
        {"nome": "Remada curvada", "nivel": "Intermediário", "series": 4, "repeticoes": 8, "equipamento": "Barra"},
        {"nome": "Puxada atrás", "nivel": "Intermediário", "series": 4, "repeticoes": 10, "equipamento": "Polia"},
        {"nome": "Remada baixa", "nivel": "Iniciante", "series": 3, "repeticoes": 12, "equipamento": "Cabo"},
        {"nome": "Levantamento terra", "nivel": "Avançado", "series": 4, "repeticoes": 6, "equipamento": "Barra"},
        {"nome": "Remada unilateral", "nivel": "Intermediário", "series": 3, "repeticoes": 10, "equipamento": "Halteres"},
        {"nome": "Pull-over", "nivel": "Avançado", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Barra fixa", "nivel": "Avançado", "series": 4, "repeticoes": 6, "equipamento": "Barra fixa"},
    ],
    "Pernas": [
        {"nome": "Agachamento livre", "nivel": "Iniciante", "series": 3, "repeticoes": 12, "equipamento": "Barra"},
        {"nome": "Leg Press", "nivel": "Intermediário", "series": 4, "repeticoes": 10, "equipamento": "Máquina"},
        {"nome": "Cadeira extensora", "nivel": "Iniciante", "series": 3, "repeticoes": 15, "equipamento": "Máquina"},
        {"nome": "Cadeira flexora", "nivel": "Intermediário", "series": 4, "repeticoes": 12, "equipamento": "Máquina"},
        {"nome": "Passada com halteres", "nivel": "Intermediário", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Stiff", "nivel": "Avançado", "series": 4, "repeticoes": 10, "equipamento": "Barra"},
        {"nome": "Agachamento sumô", "nivel": "Avançado", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Avanço no step", "nivel": "Avançado", "series": 3, "repeticoes": 12, "equipamento": "Step e Halteres"},
    ],
    "Ombros": [
        {"nome": "Desenvolvimento com halteres", "nivel": "Iniciante", "series": 3, "repeticoes": 10, "equipamento": "Halteres"},
        {"nome": "Elevação lateral", "nivel": "Intermediário", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Elevação frontal", "nivel": "Iniciante", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Desenvolvimento na máquina", "nivel": "Intermediário", "series": 4, "repeticoes": 10, "equipamento": "Máquina"},
        {"nome": "Arnold press", "nivel": "Avançado", "series": 4, "repeticoes": 8, "equipamento": "Halteres"},
        {"nome": "Remada alta", "nivel": "Avançado", "series": 3, "repeticoes": 12, "equipamento": "Barra"},
        {"nome": "Crucifixo inverso", "nivel": "Intermediário", "series": 3, "repeticoes": 15, "equipamento": "Máquina"},
        {"nome": "Desenvolvimento militar", "nivel": "Avançado", "series": 4, "repeticoes": 6, "equipamento": "Barra"},
    ],
    "Bíceps": [
        {"nome": "Rosca direta", "nivel": "Iniciante", "series": 3, "repeticoes": 10, "equipamento": "Barra"},
        {"nome": "Rosca alternada", "nivel": "Iniciante", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Rosca concentrada", "nivel": "Intermediário", "series": 3, "repeticoes": 10, "equipamento": "Halteres"},
        {"nome": "Rosca martelo", "nivel": "Intermediário", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Rosca scott", "nivel": "Intermediário", "series": 4, "repeticoes": 10, "equipamento": "Máquina"},
        {"nome": "Rosca inversa", "nivel": "Avançado", "series": 3, "repeticoes": 12, "equipamento": "Barra"},
        {"nome": "Rosca 21", "nivel": "Avançado", "series": 3, "repeticoes": 21, "equipamento": "Barra"},
        {"nome": "Rosca com corda na polia", "nivel": "Avançado", "series": 3, "repeticoes": 12, "equipamento": "Polia"},
    ],
    "Tríceps": [
        {"nome": "Tríceps testa", "nivel": "Iniciante", "series": 3, "repeticoes": 10, "equipamento": "Barra"},
        {"nome": "Tríceps coice", "nivel": "Iniciante", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Tríceps na polia", "nivel": "Intermediário", "series": 4, "repeticoes": 10, "equipamento": "Polia"},
        {"nome": "Tríceps francês", "nivel": "Intermediário", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Mergulho entre bancos", "nivel": "Intermediário", "series": 3, "repeticoes": 15, "equipamento": "Banco"},
        {"nome": "Tríceps corda", "nivel": "Avançado", "series": 3, "repeticoes": 12, "equipamento": "Polia"},
        {"nome": "Tríceps unilateral", "nivel": "Avançado", "series": 3, "repeticoes": 12, "equipamento": "Polia"},
        {"nome": "Tríceps banco", "nivel": "Avançado", "series": 3, "repeticoes": 15, "equipamento": "Banco"},
    ],
    "Trapézio": [
        {"nome": "Encolhimento com halteres", "nivel": "Iniciante", "series": 3, "repeticoes": 15, "equipamento": "Halteres"},
        {"nome": "Remada alta", "nivel": "Intermediário", "series": 3, "repeticoes": 12, "equipamento": "Barra"},
        {"nome": "Encolhimento na barra por trás", "nivel": "Avançado", "series": 3, "repeticoes": 10, "equipamento": "Barra"},
        {"nome": "Encolhimento com barra", "nivel": "Intermediário", "series": 3, "repeticoes": 12, "equipamento": "Barra"},
        {"nome": "Remada na máquina", "nivel": "Intermediário", "series": 3, "repeticoes": 10, "equipamento": "Máquina"},
        {"nome": "Remada alta com halteres", "nivel": "Avançado", "series": 3, "repeticoes": 12, "equipamento": "Halteres"},
        {"nome": "Puxada alta na polia", "nivel": "Avançado", "series": 3, "repeticoes": 10, "equipamento": "Polia"},
        {"nome": "Remada em pé com barra W", "nivel": "Avançado", "series": 3, "repeticoes": 10, "equipamento": "Barra W"},
    ]
}
